name        : ctags
version     : 5.8
release     : 5
source      :
    - http://internode.dl.sourceforge.net/project/ctags/ctags/5.8/ctags-5.8.tar.gz : 0e44b45dcabe969e0bbbb11e30c246f81abe5d32012db37395eb57d66e9e99c7
homepage    : http://ctags.sourceforge.net/
license     : GPL-2.0-or-later
component   : programming.tools
summary     : Generates an index file of language objects found in source files
description : Generates an index file of language objects found in source files
setup       : |
    %configure --disable-external-sort
build       : |
    %make
install     : |
    %make_install prefix=${installdir}/usr
